project:
  type: website
  output-dir: docs

website:
  title: "Erdem Aslanyılmaz"
  navbar:
    search: true
    left:
      - text: Anasayfa
        href: index.qmd
      - text: Hakkımda
        href: about.qmd
      - text: Gönderilerim
        href: posts.qmd
      - text: "MUY665 Ders Çıktıları"
        menu:
          - text: Ödevler
            href: portfolyo.qmd
          - text: Proje
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/erdemaslanyilmaz
      - icon: linkedin
        href: https://www.linkedin.com/in/erdem-aslanyilmaz

  sidebar:
    - title: "Çalışmalar"
      style: "docked"
      search: true
      contents:
        - portfolyo.qmd
        - portfolyo/calisma1.qmd
        - portfolyo/calisma2.qmd  
        

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - MUY665 - Bahar 2026" 
    border: true
format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc-location: left
    smooth-scroll: true
    
editor: visual